### ISSUE TITLE
Only usable when home?

### ISSUE THREAD

**Issue by dazWiLLiE** [benkuly/matrix-sms-bridge#10]
Almost got it set up when I read [this issue](https://github.com/benkuly/matrix-sms-bridge/issues/9)..

So I can only use the bridge when I'm home? Whats the point in that?
Or did I miss something?

**Comment by benkuly** [comment]
The bridge currently only can be used with two providers: Gammu or android-sms-gateway. Gammu needs a modem and android-sms-gateway a stationary smartphone. Don't use android-sms-gateway on your daily used device, because it always runs in background and starts a web server, which is accessed by the gateway.

But: you can add an provider to this bridge easily. Feel free to contribute and open a pull request.
