### ISSUE TITLE
url-to-sms-bridge?

### ISSUE THREAD

**Issue by tdehaeze** [benkuly/matrix-sms-bridge#9]
Hi,

I am currently trying to setup this sms bridge:
- I have set up android-sms-gateway-server on my android phone
- I am using matrix-docker-ansible-deploy on my homeserver

However, I don't know what should I put for the url-to-sms-bridge option?
If I understand correctly, it should point to my android phone where the server is runing.
In such case, should I connect my phone to the wifi and set a static IP address?
Could it work over 4G network?

Thanks a lot

**Comment by benkuly** [comment]
The android phone needs to be reachable from the bridge, so a static ip address or a DNS entry is needed. Then you can use something like this as baseurl: `https://192.168.2.2:9090`. 9090 is the default port of `android-sms-gateway-server`.
You could theoretically reach your phone via VPN also in a 4G network, but I don't think that makes sense, because android-sms-gateway hosts a web-server, which would drain your battery.

**Comment by tdehaeze** [comment]
Thanks a lot. Make sense.
